import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Recovery AI",
  description: "How Recovery AI collects, uses, and protects personal information.",
};

const providers = [
  ["Supabase", "authentication, account management, and database services"],
  ["OpenAI", "generating personalized Morning Brief content from your check-in"],
  ["Vercel", "website hosting and application delivery"],
  ["Cloudflare Turnstile", "bot detection and abuse prevention on the Alpha Waitlist"],
];

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#f9f7f2] text-[#14263d] selection:bg-[#dcebdc]">
      <header className="border-b border-[#14263d]/10 bg-[#f9f7f2]/95 backdrop-blur-md">
        <nav className="mx-auto flex h-[76px] max-w-[1040px] items-center justify-between px-6 md:px-10" aria-label="Privacy page navigation">
          <Link href="/" className="text-base font-semibold tracking-[-0.04em]">Recovery AI</Link>
          <div className="flex items-center gap-6 text-sm font-medium">
            <Link href="/" className="transition-colors hover:text-[#577365]">Home</Link>
            <Link href="/login" className="transition-colors hover:text-[#577365]">Sign In</Link>
          </div>
        </nav>
      </header>

      <main className="mx-auto max-w-[800px] px-6 py-16 md:px-10 md:py-24">
        <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#577365]">Legal</p>
        <h1 className="mt-5 text-5xl font-semibold tracking-[-0.06em] md:text-6xl">Privacy Policy</h1>
        <p className="mt-5 text-sm font-medium text-[#687485]">Effective Date: August 2026</p>

        <div className="mt-12 space-y-12 text-[15px] leading-7 text-[#536173] md:text-base">
          <p>
            Welcome to Recovery AI (&quot;Recovery AI,&quot; &quot;we,&quot; &quot;our,&quot; or
            &quot;us&quot;). We respect your privacy and are committed to protecting the
            information you share with us. This Privacy Policy explains what information we
            collect, how we use it, when it may be shared, and the choices available to you.
          </p>

          <PolicySection title="Information We Collect">
            <h3 className="font-semibold text-[#14263d]">Information you provide</h3>
            <p className="mt-3">Depending on how you use Recovery AI, we may collect:</p>
            <PolicyList>
              <li>Your email address when you join the Alpha Waitlist, contact us, or sign in.</li>
              <li>Authentication and account information used to provide Alpha access.</li>
              <li>Daily check-in information, including sleep, energy, mood, and the goal or intention you choose to share.</li>
              <li>Other information you voluntarily provide to us.</li>
            </PolicyList>
            <h3 className="mt-7 font-semibold text-[#14263d]">Information generated through the service</h3>
            <p className="mt-3">We generate and store information associated with your use of the product, such as recovery scores, recovery levels, insights, and personalized Morning Briefs.</p>
            <h3 className="mt-7 font-semibold text-[#14263d]">Information collected automatically</h3>
            <p className="mt-3">When you visit or use Recovery AI, we and our service providers may collect limited technical information, such as your IP address, browser and device type, operating system, timestamps, security events, and website or application usage information. This information helps us operate, secure, and improve the service.</p>
          </PolicySection>

          <PolicySection title="How We Use Your Information">
            <p>We use information to:</p>
            <PolicyList>
              <li>Manage the Alpha Waitlist and Alpha access.</li>
              <li>Authenticate users and maintain signed-in sessions.</li>
              <li>Provide daily check-ins, recovery insights, and Morning Briefs.</li>
              <li>Communicate service messages and meaningful product updates.</li>
              <li>Respond to inquiries and support requests.</li>
              <li>Improve Recovery AI and understand product performance.</li>
              <li>Detect abuse, maintain security, and comply with legal obligations.</li>
            </PolicyList>
            <p className="mt-4 font-medium text-[#14263d]">We do not sell your personal information.</p>
          </PolicySection>

          <PolicySection title="AI Processing">
            <p>When you request a Morning Brief, information from your check-in and the recovery context generated by Recovery AI is sent to OpenAI to produce the requested content. Please do not include information that is unnecessary for your check-in, and do not use Recovery AI to communicate a medical emergency.</p>
          </PolicySection>

          <PolicySection title="Cookies and Similar Technologies">
            <p>Recovery AI uses cookies and similar technologies that are necessary for authentication, session management, security, and core website functionality. Our providers may also use these technologies to deliver and protect the service. We do not currently use advertising cookies. You can control cookies through your browser settings, but disabling essential cookies may prevent sign-in or other product features from working.</p>
          </PolicySection>

          <PolicySection title="Service Providers and Sharing">
            <p>We use third-party providers to operate Recovery AI. These providers may process information for the purposes described below:</p>
            <ul className="mt-4 space-y-3">
              {providers.map(([name, purpose]) => (
                <li key={name} className="rounded-xl border border-[#14263d]/10 bg-white px-5 py-4">
                  <span className="font-semibold text-[#14263d]">{name}</span>
                  <span> — {purpose}.</span>
                </li>
              ))}
            </ul>
            <p className="mt-4">We may also disclose information when required by law, to protect our rights or users, or in connection with a merger, financing, acquisition, or transfer of all or part of our business. We do not rent your personal information to third parties.</p>
          </PolicySection>

          <PolicySection title="Data Retention">
            <p>We retain personal information only for as long as reasonably necessary to provide and improve the service, manage Alpha access, meet our legal obligations, resolve disputes, and enforce our agreements. Retention periods may vary based on the type of information and why it was collected.</p>
          </PolicySection>

          <PolicySection title="Data Security">
            <p>We use reasonable technical and organizational measures designed to protect personal information. However, no method of internet transmission or electronic storage is completely secure, and we cannot guarantee absolute security.</p>
          </PolicySection>

          <PolicySection title="International Processing">
            <p>Recovery AI and its service providers may process information in countries other than the country where you live. Where required, we take appropriate steps to protect information transferred across borders.</p>
          </PolicySection>

          <PolicySection title="Your Rights and Choices">
            <p>Depending on where you live, you may have the right to access, correct, or delete your personal information, object to or restrict certain processing, or withdraw consent where processing is based on consent. You may also opt out of non-essential product updates. These rights may be subject to legal limitations and verification of your request.</p>
            <ContactLine prefix="To make a request, email" />
          </PolicySection>

          <PolicySection title="Children's Privacy">
            <p>Recovery AI is not directed to children under the age of 13, and we do not knowingly collect personal information from children under 13. If you believe a child has provided us with personal information, please contact us so we can take appropriate action.</p>
          </PolicySection>

          <PolicySection title="Changes to This Policy">
            <p>We may update this Privacy Policy from time to time. The latest version will be available on this page, and we will update the effective date when material changes are made.</p>
          </PolicySection>

          <PolicySection title="Contact">
            <ContactLine prefix="If you have questions about this Privacy Policy or how Recovery AI handles personal information, contact us at" />
          </PolicySection>
        </div>
      </main>

      <footer className="border-t border-[#14263d]/10">
        <div className="mx-auto flex max-w-[1040px] flex-col gap-3 px-6 py-8 text-xs text-[#748091] md:flex-row md:items-center md:justify-between md:px-10">
          <p>© 2026 Recovery AI. All rights reserved.</p>
          <Link href="/" className="transition-colors hover:text-[#14263d]">Back to Recovery AI</Link>
        </div>
      </footer>
    </div>
  );
}

function PolicySection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-2xl font-semibold tracking-[-0.035em] text-[#14263d]">{title}</h2>
      <div className="mt-4">{children}</div>
    </section>
  );
}

function PolicyList({ children }: { children: React.ReactNode }) {
  return <ul className="mt-3 list-disc space-y-2 pl-6 marker:text-[#577365]">{children}</ul>;
}

function ContactLine({ prefix }: { prefix: string }) {
  return (
    <p className="mt-4">
      {prefix}{" "}
      <a href="mailto:contact@recoverybrief.com" className="font-medium text-[#14263d] underline decoration-[#577365]/40 underline-offset-4 hover:decoration-[#14263d]">
        contact@recoverybrief.com
      </a>
      .
    </p>
  );
}
